### PR TITLE
fix: asyncio import, removed model revision pinning and table grouping arg

### PR DESCRIPTION
**Pull request by vadakattu**

### CODE REVIEW

**Comment by vadakattu** [comment]
@polong-lin @alokpattani Seems owlbot post processor keeps eating the asyncio import line

**Comment by holtskinner** [comment]
> @polong-lin @alokpattani Seems owlbot post processor keeps eating the asyncio import line

Autoflake is removing the import because it's not being used in the notebook. Why is asyncio needed?

**Comment by vadakattu** [comment]
> > @polong-lin @alokpattani Seems owlbot post processor keeps eating the asyncio import line
> 
> Autoflake is removing the import because it's not being used in the notebook. Why is asyncio needed?

@holtskinner the second half of the notebook is about async execution to process multiple videos. It's problem with the linter not understanding the import is necessary to execute L1012 `multiple_video_extraction_responses = await asyncio.gather(*get_responses)`

**Comment by holtskinner** [comment]
> > > @polong-lin @alokpattani Seems owlbot post processor keeps eating the asyncio import line
> > 
> > 
> > Autoflake is removing the import because it's not being used in the notebook. Why is asyncio needed?
> 
> @holtskinner the second half of the notebook is about async execution to process multiple videos. It's a problem with the linter not understanding the import is necessary to execute L1012 `multiple_video_extraction_responses = await asyncio.gather(*get_responses)`

Thanks for that context, I missed the usage. Not sure what's going on here. I'll do some experimentation

**Review by holtskinner — APPROVED** [review]

**Pull request merged**
