### PR TITLE
fix: removing installation as a user

### PR DESCRIPTION
**Pull request by alokSureskills**
# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [ ] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [ ] You are listed as the author in your notebook or README file.
  - [ ] Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).
- [ ] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [ ] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by holtskinner** [comment]
Why is this being removed? We also need to keep `--upgrade`

**Comment by holtskinner** [comment]
> > Why is this being removed? We also need to keep `--upgrade`
> 
> Yes, you are correct we don't need to remove the upgrade flag, we just need to remove the user flag. I made the new commit with the changes. Thanks

Why do we need to remove the user flag?

**Comment by alokSureskills** [comment]
> > > Why is this being removed? We also need to keep `--upgrade`
> > 
> > 
> > Yes, you are correct we don't need to remove the upgrade flag, we just need to remove the user flag. I made the new commit with the changes. Thanks
> 
> Why do we need to remove the user flag?

This causes pip to install the package for the current user alone rather than the entire system when we run the command to install the packages with the --user parameter. As a result, we see this error when we run the following cell.
Attached is the screenshot

image

It functions flawlessly when we remove the --user flag and install the package system-wide.
It will be necessary to remove the "--user" parameter for this reason.

**Comment by holtskinner** [comment]
Ok, that's strange, it shouldn't make a difference, but I suppose we can change it

**Review by holtskinner — APPROVED** [review]

**Comment by holtskinner** [comment]
Ok, that's strange, it shouldn't make a difference, but I suppose we can change it

**Pull request merged**
