### PR TITLE
Folder restructuring for clarity

### PR DESCRIPTION
**Pull request by polong-lin**

### CODE REVIEW

**Review by holtskinner — APPROVED** [review]

**Comment by erwinh85** [comment]
LGTM. Can we also cleane up some of the files in GoogleCloudPlatform/generative-ai/ ?

**Comment by mattvail-accenture** [comment]
This refactor causes the automatic test to fail on the courses, for example `language/examples/prompt-design/` was changed to `language/prompt/examples' https://partner.cloudskillsboost.google/focuses/68883?parent=catalog

I am all for the refactoring, just need the courses to be updated as well.

**Comment by polong-lin** [comment]
We are trying to fix this ASAP -- sorry about this, @mattvail-accenture !

**Comment by mattvail-accenture** [comment]
No worries it happens, Thank you for fixing it @polong-lin . All this information was really great to have.

**Pull request merged**
