### PR TITLE
Variable name in 'reduce' step

### PR DESCRIPTION
**Pull request by the-data-guy**
Function argument is "_summary_" while what is being used in the function is '_initial_summary_'. Fixing this.

### CODE REVIEW

**Comment by polong-lin** [comment]
Hi @the-data-guy , could you kindly reduce the files changed to just what you are describing with the summary variable fix? Thanks!

**Comment by the-data-guy** [comment]
Oops. Sorry about that. Please check now.

**Comment by the-data-guy** [comment]
Reopened after incorporating feedback by @polong-lin

**Comment by erwinh85** [comment]
@iamthuya can you have a look?

**Comment by iamthuya** [comment]
Thanks for flagging this @the-data-guy. I have renamed the function parameter to `initial_summary` to reflect better. Will be closing this.

**Pull request merged**
