### PR TITLE
fix: Updated the code to install Python SDK

### PR DESCRIPTION
**Pull request by anjalikumari-ssk**
- Updated the command to install Python SDK.
- Related Buganizer: http://b/332484008

### CODE REVIEW

**Comment by holtskinner** [comment]
@anjalikumari-ssk What's the specific reason to remove the `--quiet` from the pip install? Do we need to change this for other notebooks used in Qwiklabs?

**Comment by anjalikumari-ssk** [comment]
Hi @holtskinner,

While performing the lab `Getting Started with Vector Search and Embeddings` I encountered the error while running the cell to install Python SDK in the notebook `intro-textemb-vectorsearch.ipynb`. 

I have mentioned the error details on the buganizer: http://b/332484008

As, a workaround I have updated the command to **install python SDK** and was able to run the cell successfully and proceed further with the lab.

Thanks!

**Comment by holtskinner** [comment]
I'm not sure how removing the `--quiet` flag would make a difference. This behavior would also occur with other notebooks. I think this issue is better resolved on the Qwiklabs side with the specific environments being provisioned.

**Comment by anjalikumari-ssk** [comment]
Hi @holtskinner,

The lab **Getting Started with Vector Search and Embeddings** is going to be used in the Next'24 event and is the priority task. It would be very helpful if you could merge this PR with the temporary changes so that user won't get affected due to the dependency issue.

Thanks!

**Review by holtskinner — APPROVED** [review]

**Pull request merged**
