### PR TITLE
feat: new function calling claude nb

### PR DESCRIPTION
**Pull request by nikitamaia**
# Description

Claude multimodal function calling notebook

### CODE REVIEW

**Review by koverholt — APPROVED** [review]
Thanks for this notebook on our wonderful partner models! Apologies for the weird formatting of review comments with ReviewNB, the raw notebook was not rendering for me in the typical GitHub view for the notebook code.

Just left some minor comments on formatting and adding links. Otherwise LGTM!

**Comment by nikitamaia** [comment]
<p>like this? </p><p>%pip install --upgrade --user --quiet google-cloud-aiplatform 'anthropic[vertex]' wikipedia</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689832'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikitamaia** [comment]
<p>This reference? <a href="https://docs.anthropic.com/en/api/messages" target="_blank">https://docs.anthropic.com/en/api/messages</a></p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689899'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by koverholt** [comment]
<p>Yep, or for better readability, esp., for longer lists of packages:</p><p> </p>

<pre class="ql-syntax" spellcheck="false">%pip install --upgrade --user --quiet \
&nbsp; &nbsp; google-cloud-aiplatform \
&nbsp; &nbsp; "anthropic[vertex]" \
&nbsp; &nbsp; wikipedia
</pre><p> </p><p>Also, does this notebook actually require the <code>google-cloud-aiplatform</code> package? Or the vertex AI initialization? I don't know enough about how their SDK works to know if it depends on or needs the Vertex AI Python SDK.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689832'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by koverholt** [comment]
<p>Yep, I wish there was a friendlier page than the API docs, but that is the best page I could find as well.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689899'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikitamaia** [comment]
<p>Seems like google-cloud-aiplatform is not required. neither is the vertex ai initialization. I will remove.</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689832'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by koverholt** [comment]
<p>Nice! Yes I just tested that as well and confirmed. However, it made me realize:</p><p> </p><ol><li>You should add a link to docs to enable Claude model(s) in Model Garden</li><li>You can definitely remove the cell for vertex AI init, just be sure the user defines their PROJECT_ID somewhere for this line <code>client = AnthropicVertex(region=LOCATION, project_id=PROJECT_ID)</code></li></ol>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689832'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by nikitamaia** [comment]
<p>Oh yes. Good shout. I'll add that link</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/generative-ai/pull/1337/discussion/#comment-2438689832'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by koverholt** [comment]
Tested and all is working great. Thanks again for this notebook example! LGTM.

**Pull request merged**
