### PR TITLE
copying from vector-search to embedding

### PR DESCRIPTION
**Pull request by kazunori279**
Copying the notebooks with a few fixes. After updating the existing links to the vertex-search notebooks on public documents, we will remove /vector-search folder and use /embeddings for future updates.

### CODE REVIEW

**Review by erwinh85 — APPROVED** [review]
LGTM

**Comment by erwinh85** [comment]
LGTM

**Comment by polong-lin** [comment]
@kazunori279 As we currently have notebooks duplicated in both vector-search and embeddings, it makes it difficult for any fixes when double-sourced like https://github.com/GoogleCloudPlatform/generative-ai/pull/265.

Could you create a PR to remove the vector-search/ folder as soon as possible, if the public documentation links are ready?

**Comment by kazunori279** [comment]
Sure, I will send a PR as soon as the links on the documents replaced with the /embeddings. Please let me know if you need the PR ASAP.

**Pull request merged**
