### PR TITLE
feat: Add GitHub action to add `owlbot:run` label to newly opened PRs

### PR DESCRIPTION
**Pull request by koverholt**
# Description

Thank you for opening a Pull Request!
Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [X] Follow the [`CONTRIBUTING` Guide](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CONTRIBUTING.md).
- [ ] ~You are listed as the author in your notebook or README file.~
  - [ ] ~Your account is listed in [`CODEOWNERS`](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/.github/CODEOWNERS) for the file(s).~
- [X] Make your Pull Request title in the <https://www.conventionalcommits.org/> specification.
- [X] Ensure the tests and linter pass (Run `nox -s format` from the repository root to format).
- [X] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Review by holtskinner — APPROVED** [review]

**Comment by koverholt** [comment]
@holtskinner:

The labeling part of this PR is working as expected. But the OwlBot logs don't look quite right to me, not sure if I'm testing or invoking it in an odd way. I can merge and we can try OwlBot in new test PRs if that works for you?

```
tep #5: Skipping: samples/AUTHORING_GUIDE.md
Step #5: Skipping: samples/CONTRIBUTING.md
Step #5: scripts/decrypt-secrets.sh
Step #5: scripts/readme-gen/readme_gen.py.j2
Step #5: scripts/readme-gen/templates/README.tmpl.rst
Step #5: scripts/readme-gen/templates/auth.tmpl.rst
Step #5: scripts/readme-gen/templates/auth_api_key.tmpl.rst
Step #5: scripts/readme-gen/templates/install_deps.tmpl.rst
Step #5: scripts/readme-gen/templates/install_portaudio.tmpl.rst
Step #5: setup.cfg
Step #5: testing/.gitignore
Step #5:     s.shell.run(["nox", "-s", "format"], hide_output=False)
Step #5:   File "/synthtool/synthtool/shell.py", line 39, in run
Step #5:     raise exc
Step #5:   File "/synthtool/synthtool/shell.py", line 27, in run
Step #5:     return subprocess.run(
Step #5:   File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
Step #5:     raise CalledProcessError(retcode, process.args,
Step #5: subprocess.CalledProcessError: Command '['nox', '-s', 'format']' returned non-zero exit status 1.
Finished Step #5
```

**Comment by holtskinner** [comment]
That behavior is really weird. Maybe change the glob rule to add only when `.py`/`.ipynb` files are edited?

**Comment by koverholt** [comment]
Oh neat, in the latest run OwlBot is happy, so I think it just didn't like some of my test invocations. I will merge and open a new PR with intentional lint failures in Python files to test. And I can test again with non-Python files to see if that error comes up again and if I need to change glob rules. Thanks!

**Comment by koverholt** [comment]
@holtskinner, one other question. Do we want the `owlbot:run` label to only be applied by the action only when the PR is initially opened? Or some additional trigger(s)? Want to make sure that I reduce noise as much as possible (e.g., not on every commit) but have it run as often as we like.

**Pull request merged**
