### PR TITLE
chore: Add Repo Automation Configs

### PR DESCRIPTION
**Pull request by holtskinner**
- Owlbot/Noxfile
  - Runs on each pull request, does autoformatting with Black
- Renovate
  - Create Automated Pull Requests to update Packages
- Github super linter (Linter for lots of languages)
  - Blocks pull requests that don't satisfy the linter

### CODE REVIEW

**Review by iamthuya — APPROVED** [review]
LGTM

**Comment by holtskinner** [comment]
Thank you! I don't have write access, so someone with it will need to merge this PR

**Review by Precha24 — APPROVED** [review]

**Review by Precha24 — APPROVED** [review]

**Comment by Precha24** [comment]
#49

**Review by Precha24 — COMMENTED** [review]
Good

**Pull request merged**
