### PR TITLE
Fixed broken links as suggested in issue #82

### PR DESCRIPTION
**Pull request by yogeshhk**
https://github.com/GoogleCloudPlatform/generative-ai/issues/82

### CODE REVIEW

**Comment by yogeshhk** [comment]
@polong-lin will you be able to review this PR?

**Review by shakeebshams — APPROVED** [review]
LGTM

**Comment by yogeshhk** [comment]
@erwinh85 are PR#97 changes merged?

**Comment by holtskinner** [comment]
Not sure why this wasn't merged before, but I created a new PR to fix these broken links #338

**Pull request closed without merging**
